{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "slm-server.fullname" . }}
  labels:
    {{- include "slm-server.labels" . | nindent 4 }}
spec:
  storageClassName: {{ include "slm-server.fullname" . }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
