apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "slm-server.fullname" . }}
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
